const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
const GET_MOBILE_PRODUCT = "GET_MOBILE_PRODUCT";
const GET_CAMERA_PRODUCT = "GET_CAMERA_PRODUCT";
const GET_TABLET_PRODUCT = "GET_TABLET_PRODUCT";
const GET_LAPTOP_PRODUCT = "GET_LAPTOP_PRODUCT";
const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
const GET_CART_DETAILS = "GET_CART_DETAILS";
export {GET_CART_DETAILS,GET_ALL_PRODUCT,GET_MOBILE_PRODUCT,GET_CAMERA_PRODUCT,GET_TABLET_PRODUCT,GET_LAPTOP_PRODUCT,GET_ALL_CATEGORY};